Content:
    open_pronghorn:
        root_dir: ${ROOT_DIR}/doc/content
    framework:
        root_dir: ${MOOSE_DIR}/framework/doc/content
    modules:
        root_dir: ${MOOSE_DIR}/modules/doc/content
        content:
            - help/development/VSCode.md
            - help/development/analyze_jacobian.md
            - help/finite_element_concepts/nodal_patch_recovery.md
            - application_development/performance_benchmarking.md
            - application_usage/restart_recover.md
            - application_usage/command_line_usage.md
    navier_stokes:
        root_dir: ${MOOSE_DIR}/modules/navier_stokes/doc/content
    fluid_properties:
        root_dir: ${MOOSE_DIR}/modules/fluid_properties/doc/content
    heat_transfer:
        root_dir: ${MOOSE_DIR}/modules/heat_transfer/doc/content
    ray_tracing:
        root_dir: ${MOOSE_DIR}/modules/ray_tracing/doc/content
    rdg:
        root_dir: ${MOOSE_DIR}/modules/rdg/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    extra-css:
        - css/open_pronghorn.css
    extra-js:
        - logo_belt.js
Extensions:
    MooseDocs.extensions.navigation:
        name: OpenPronghorn
        repo: https://github.com/idaholab/open_pronghorn
        menu:
            Validation: resources/filter/index.html
            Documentation:
                OpenPronghorn-only Syntax: syntax/open_pronghorn_only.md
                Complete Code Syntax: syntax/index.md
            Software Quality:
                Software Quality Assurance (SQA) Information: /sqa/index.md
                Code Standards: sqa/open_pronghorn_scs.md
            Theory:
                Introduction: theory/introduction.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - include
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms:
            framework: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        active: true
        categories:
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            open_pronghorn: !include ${ROOT_DIR}/doc/sqa_open_pronghorn.yml
            fluid_properties: !include ${MOOSE_DIR}/modules/fluid_properties/doc/sqa_fluid_properties.yml
            heat_transfer: !include ${MOOSE_DIR}/modules/heat_transfer/doc/sqa_heat_transfer.yml
            navier_stokes: !include ${MOOSE_DIR}/modules/navier_stokes/doc/sqa_navier_stokes.yml
            rdg: !include ${MOOSE_DIR}/modules/rdg/doc/sqa_rdg.yml
            ray_tracing: !include ${MOOSE_DIR}/modules/ray_tracing/doc/sqa_ray_tracing.yml
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
    MooseDocs.extensions.tagging:
        active: True
        js_file: index-6fae072b.js
        allowed_keys:
            - compressibility
            - heattransfer
            - convection_type
            - transient
            - flow_regime
            - fluid
            - flow_configuration
            - number_of_phases
